apiVersion: v1
kind: Service
metadata:
  name: {{ include "slack-bot.fullname" . }}
  labels:
    {{- include "slack-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "slack-bot.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 443